@startuml


title Clinical Categorization Resources

  object Patient {
    identifier: NHS Number
  }

    object Organization {
      identifier: ODS Code
    }

package ClinicalCategorization as "Clinical Categorization" {
    object EpisodeOfCare {
      patient
      managingOrganization
    }

    object Encounter {
     subject
     episodeOfCare
     serviceProvider
     appointment
    }

    object Flag {
    subject
    }

}


EpisodeOfCare "patient" }o--o|  Patient
EpisodeOfCare "managingOrganizationr" }o--o|  Organization
Encounter "subject" }o--o|  Patient
Encounter "serviceProvider" }o--o|  Organization
Encounter "appointment" }o--o| Appointment
Flag "subject" }o--o|  Patient


@enduml
