@startuml

title Service Provider Directory Resources


  object Practitioner {
    identifier: GMC, GMP, etc code
  }


package ProviderDirectory as "Provider Directory" {
    object Organization {
      identifier: ODS Code
    }

    object HealthcareService {
      providedBy
      location
    }
    object PractitionerRole {
      identifier: sdsRoleProfileID
      practitioner
      organization
      healthcareService
    }

    object Endpoint {
      managingOrganization
    }
    object Location {
      managingOrganization
    }
}

HealthcareService "providedBy" }o--o|  Organization
HealthcareService "location" }o--o|  Location
Location "managingOrganization" }o--o|  Organization
Endpoint "managingOrganization" }o--o|  Organization
PractitionerRole "organization" }o--o|  Organization
PractitionerRole "healthcareService" }o--o|  HealthcareService
PractitionerRole "practitioner" }o--o|  Practitioner


@enduml
