@startuml


title Patient Registers


package PatientRegisters as "Patient Registers" {
  object Patient {
    identifier: NHS Number
    name
    gender
    telecom
    birthdate
    address
    link
  }
  object RelatedPerson  {
  identifier: NHS Number
    patient
    name
    gender
    telecom
    birthdate
    address
  }
  object Practitioner  {
    identifier: GMC, GMP, etc code
    qualification
    name
    telecom
  }
  object Person {
    identifier
    name
    gender
    telecom
    birthdate
    address
    link
  }

  Patient ..> "link" Person
   Patient --> "link" Patient : De duplication \nreplaced-by | replaces | refer | seealso
  RelatedPerson ..> "link" Person
  Practitioner ..> "link" Person
}

@enduml
