@startuml


title Patient Registers


package PatientRegisters <<Frame>> as "Patient Registers" {
  class Patient implements Person {
    identifier: NHS Number
  }
  class RelatedPerson implements Person {
    patient
  }
  class Practitioner implements Person {
    identifier: GMC, GMP, etc code
  }
  class Person
  
}

@enduml
