@startuml

title Scheduling and Appointments


  object Patient {
    identifier: NHS Number
  }

  object Practitioner {
    identifier: GMC, GMP, etc code
  }


    object HealthcareService {
      providedBy
      location
    }


    object Location {
      managingOrganization
    }



  object Encounter {
   subject
   episodeOfCare
   serviceProvider
   appointment
  }



package Scheduling as "Scheduling and Appointments" {
  object Schedule {
    actor
  }

  object Slot {
    schedule
  }

  object Appointment {
    slot
    participant.actor
  }

  object AppointmentResponse {
    appointment
    actor
  }

}


Encounter "appointment" }o--o| Appointment
Schedule "actor" }o--o|  Practitioner
Schedule "actor" }o--o|  HealthcareService
Schedule "actor" }o--o|  Location

Slot "schedule" }o--o| Schedule
Appointment "slot" |o--o{ Slot
Appointment "participant.actor" }o--o{ Patient
Appointment "participant.actor" }o--o{ Practitioner
Appointment "participant.actor" }o--o{ Location
Appointment "participant.actor" }o--o{ RelatedPerson

AppointmentResponse "appointment" ||--o{ Appointment
AppointmentResponse "actor" }o--o{ Patient
AppointmentResponse "actor" }o--o{ Practitioner
AppointmentResponse "actor" }o--o{ RelatedPerson


@enduml
