@startuml

hide footbox

title "Respond to an Appointment request"


participant "Appointment Provivider" as provider
participant "Appointment Participant" as participant


provider -> participant : (Event notification) POST /Appointment \n e.g. Teams Meeting invite
participant --> provider : 200 OK
participant -> provider : POST /AppointmentResponse (accept, decline or maybe) \n e.g. Respond to Teams Meeting invite
provider --> participant : 200 OK
opt if appointment is no longer viable
provider -> participant : (Event notification) POST /Appointment (cancelled) \n e.g. Teams Meeting organiser cancels meeting
participant --> provider : 200 OK
end


@enduml
