@startuml

hide footbox

title "Search for free slots and Book an appointment"


participant Consumer
participant Provider


Consumer -> Provider : GET /Slot?start={start}&end={end}&searchFilter={filter} or GET /Slot?start={start}&end={end}&service={filter}
Provider --> Consumer : Slots
Consumer -> Provider : POST /Appointment
Provider --> Consumer : 201 Created


@enduml
