@startuml
skinparam svgDimensionStyle false
hide footbox
participant "Care Team Contributor" as Client
participant "Care Team Service" as Server
activate "Client"
"Client" -> "Server" : Search for Care Team [PCC-46] \nRetrieve Care Team [PCC-47]\nUpdate Care Team [PCC-45]
activate "Server"
"Server" --> "Client" : Response
deactivate "Client"
deactivate "Server"
@enduml
