@startuml


title Care Planning

package CarePlanning as "Care Planning" {

class CarePlan {
    patient,
    instantiatesCanonical,
    goal,
    careTeam,
    activity: Planned and Completed
}

class Goal {

}

class CareTeam {

}

class Assessments as "Assesments \n(Structured Data Capture)" {
  forms: e.g. EOLC, ReSPECT, UCP, etc

}
}

package Workflow {

class Task {
}

}

package SharedCareRecord {

class RecordArtefacts {
}


}

CarePlan "goal" |o--o{ Goal
CarePlan "careTeam" |o--o{ CareTeam
CarePlan |o--o{ Task: Arranging activities on a Care Plan
CarePlan |o--o{ RecordArtefacts
CarePlan "instantiatesCanonical" ||--|| Assessments : CarePlan is probably initially derived from an Assessment

@enduml
