@startmindmap

title Care Coordination

* Care Coordination
** Interoperability Standards
*** Data
**** FHIR RESTful API
***** Workflow
****** Workflow Brokers (e.g. eRS and EPS)
****** Conversations (FHIR Workflow)
***** Event Notification
****** FHIR Subscription
****** FHIR Cast
**** Messaging
***** FHIR Messaging)
****** 302 Legacy - See FHIR Workflow and Events
***** HL7 v2 Messaging)
****** 302 Legacy - See FHIR Workflow and Events
*** Document
**** XML/SOAP
***** IHE XDS
**** FHIR RESTful API
***** IHE MHD
**** email/fax Notifications
***** 302 Legacy - See FHIR Workflow and Events
**** format
***** pdf, html, doc, etc
***** Hybrid (Data + Document)
****** Europe Laboratory Report (FHIR Document)

** Content (Data Standards)
*** Request
**** Referral Letters
**** Laboratory Order
**** Prescription
*** Event
**** Transfer of Care
***** Outpatient Letters
***** Discharge Letters
**** Laboratory Reports
**** Pharmacy




@endmindmap
