@startmindmap


title Assesments and Care Planning


* Assesments and Care Planning
** Interoperability Standards
*** Data
**** Forms (FHIR Structured Data Capture)
**** Care Teams (IHE Dynamic Care Team Managment)
**** Care Plans (IHE Dynamic Care Planning)
*** Document
**** IHE XDS and/or MHD (FHIR RESTful)
**** pdf, html, doc, etc
**** Hybrid (Data + Document)

** Content (Data Standard examples)
*** ReSPECT (Recommended Summary Plan for Emergency Care and Treatment) form
*** End of life care plan
*** End of Life Care Coordination Summary
*** Contingency plan
*** Emergency Health Care Plans
*** Mental Health Crisis Plan
*** PRSB
**** About Me
**** Personalised Care and Support Plan




@endmindmap
