@startmindmap


title Shared Care Records


* Patient Summary
** Interoperability Standards
*** Data
**** International Patient Access (FHIR RESTful)
**** IHE Query for Existing Patient Data (FHIR RESTful)
**** UK Core FHIR Access (FHIR RESTful)
**** Care Connect RESTful API (FHIR STU3 -> R4?)
*** Document
**** IHE XDS and/or MHD (FHIR RESTful)
**** pdf, html, doc, etc
**** Hybrid (Data + Document)
***** International Patient Summary (FHIR Document)

** Content (Data Standards)
*** Allergies
*** Problems
*** Medications
*** Vaccinations
*** Results
*** Procedures
*** Vital Signs
**** Royal College of Physicians NEWS2 (National Early Warning Score 2) chart
*** Etc




@endmindmap
