@startuml

skinparam actorStyle awesome


package Consenter {
  actor "General Practitioner" as pad
  actor "Automatic Consent" as auto
}

actor Proxy as pat

usecase "Consent to act as a proxy" as CON

pat -- CON : Request proxy access
auto -- CON : Authorise proxy access
pad -- CON : Authorise proxy access


@enduml
