@startuml

title Example Laboratory Order Process

state ServiceRequeststatus as "ServiceRequest.status" {
}

state Taskstatus as "Task.status (Order Fulfilment)" {
}

state DiagnosticReportstatus as "DiagnosticReport.status" {
}

[*] --> ServiceRequeststatus.active
ServiceRequeststatus.active --> Taskstatus.requested
note on link
  This is requesting the order be performed
end note
Taskstatus.requested --> Taskstatus.rejected
Taskstatus.requested --> Taskstatus.accepted
Taskstatus.requested --> Taskstatus.cancelled
Taskstatus.accepted --> DiagnosticReportstatus.final
note on link
  The order is acted on and DiagnosticReports are created
end note
Taskstatus.rejected --> Taskstatus.requested
note on link
  The fuliller has declined to perform the order
end note

DiagnosticReportstatus.final --> Taskstatus.completed
Taskstatus.completed --> ServiceRequeststatus.completed
Taskstatus.cancelled --> ServiceRequeststatus.revoked
ServiceRequeststatus.completed --> [*]
ServiceRequeststatus.revoked --> [*]

@enduml
