@startuml

title Diagnostics


package RequestAndReport as "Request and Report" {

  object ServiceRequest {
    subject: patient
    category: laboratory procedure | imaging
    requester: Who/what is requesting service
    performer: Requested performer
  }
  object DiagnosticReport {
    subject: patient
    category: Laboratory, Radiology, Genetics, etc
    effective[x]
    basedOn
    result
    imagingStudy
    presentedForm
    media
  }
  object Specimen {
   subject: patient
   request
  }


}

package Results as "Results" {
  object Observation {
    subject: patient
    effective[x]
    hasMember
  }
  object ImagingStudy {
     subject: patient
  }
  object Media {
     subject: patient
  }
}

object Binary

note "would be in its native format \nand not normally a FHIR resource \n\n e.g. PDF, etc" as raw

raw .. Binary

DiagnosticReport "basedOn" }o--o| ServiceRequest
Specimen "request" }o--o| ServiceRequest
DiagnosticReport "result" }o--o| Observation
DiagnosticReport "imagingStudy" }o--o| ImagingStudy
DiagnosticReport "presentedForm" }o--o| Binary
DiagnosticReport "media" }o--o| Media
Observation "hasMember" }o--o| Observation : Group Lab

@enduml
