@startuml

title Documents

mix_actor "Document Source" as documentSource


class "Document Registry (DocumentReference)" as documentRegistry {
   subject: patient
   type
   author
   custodian
   description
   content.url
   context.practiceSetting
   FindDocumentReferences(ITI-67): GET /DocumentReference
   RetrieveDocumentPointers(NRL): GET /DocumentReference
   CreateDocumentPointer(NRL): POST /DocumentReference
   UpdateDocumentPointer(NRL): PUT /DocumentReference/{id}
}


class "Document Repository (Binary)" as documentRepository {
  RetrieveDocument() : GET /Binary or {pointerUrl}

}

class "Data Repository (any)" as dataRepository {
  RetrievePointer() : GET {pointerUrl}
}



mix_actor "Document Consumer" as documentConsumer


documentSource --> documentRepository : Simplified Publish [IHE MHD ITI-105] \n Provide and Register Document Set [IHE XDS ITI-41]
documentRepository --> documentRegistry : Register DocumentSet
documentRepository }o--o| "content.url" documentRegistry: pointer
dataRepository }o--o| "content.url" documentRegistry: pointer
documentSource --> documentRegistry: NRL POST \DocumentReference \n NRL PUT \DocumentReference
documentConsumer --> documentRegistry: Find Document References [IHE MHD ITI-67] \n NRL GET \DocumentReference
documentConsumer --> documentRepository: Retrieve Document [IHE MHD ITI-68]\n NRL GET \{pointerUrl}
documentConsumer --> dataRepository: NRL GET \{pointerUrl}

note "would be in its native format \nand not normally a FHIR resource if it is a document \n e.g. PDF, etc" as raw
note "This is NRL and core of IHE MHD (and IHE XDS)" as nrl
note "Not defined in NRL but focus of HL7 and IHE standards \n for sharing care data and documents" as ihe


raw .. documentRepository
nrl .. documentRegistry
ihe .. dataRepository
ihe .. documentRepository

@enduml
