@startuml


title Cross Enterprise Document Sharing (XDS on FHIR (MHD))

hide footbox

actor user
participant DocumentRegistry
participant DocumentRepository as "Document Repository"


user -> DocumentRegistry : Find Document References \n[[https://profiles.ihe.net/ITI/MHD/ITI-67.html ITI-67]]
DocumentRegistry --> user: Matching IHE Document metadata / FHIR DocumentReference
user -> user: Select Document
opt
user -> DocumentRepository : Retrieve Document \n[[https://profiles.ihe.net/ITI/MHD/ITI-68.html ITI-68]]
DocumentRepository -> user: PDF or [[https://hl7.org/fhir/R4/documents.html FHIR Document]] (Discharge Reports and Clinic Letters)

end

@enduml
