@startgantt

-- Data Standards --

 [Record Standards (ISO 13606] as [record] lasts 2 week and 3 days


-- Enterprise Architecture --

[IHE Mobile access to Health Documents (MHD)] as [MHD] lasts 3 week
[IHE Query for Existing Data Mobile (QEDm)] as [QEDm] lasts 3 week
[IHE Patient Demographics Query (PDQm)] as [PDQm] lasts 3 weeks and 3 days
[IHE Patient Identifier Cross-referencing for mobile (PIXm)] as [PIXm] lasts 3 weeks and 3 days


-- Interoperability Standards --

    [Foundation Clinical API (for HIoW, NWCancer and NWCancer)] as [share] lasts 4 weeks
  [Demographics (for PDS, PAS and MPI)] as [Demographics] lasts 3 weeks


  -- Data Standards --

 [Specialty Record Standards (e.g. ReSPECT)] as [otherrecord] lasts 2 weeks and 3 days

-- Enterprise Architecture --


 [IHE Retrieve Form for Data Capture] as [RFDC] lasts 2 week


-- Interoperability Standards --

 [FHIR Structure Data Capture] as [SDC] lasts 2 week

  [SDC + Workflow (e.g. ReSPECT for NW Cancer and YHCR] as [SDCworkflow] lasts 4 week

   -- Data Standards --
 [ContSys (ISO 13940)] as [contSys] lasts 2 week and 3 days


-- Enterprise Architecture --

 [IHE Dynamic Care Planning (DCP)] as [DCP] lasts 2 week
  [IHE Dynamic Care Teams (DCT)] as [DCT] lasts 2 week


-- Interoperability Standards --


  [Workflow (for HIoW and NWCancer)] as [W] lasts 2 week





 [DCT] starts at [contSys]'s end
 [DCP] starts at [contSys]'s end
 [W] starts at [record]'s end
 [W] starts at [QEDm]'s end
[W] starts at [MHD]'s end
[SDC] starts at [RFDC]'s end
[SDCworkflow] starts at [otherrecord]'s end
[SDCworkflow] starts at [SDC]'s end
[share] starts at [QEDm]'s end
[share] starts at [MHD]'s end
[Demographics] starts at [PDQm]'s end
[Demographics] starts at [PIXm]'s end


@endgantt
