@startuml


title National Proxy Service

object Consent {
  * status: proposed | active | rejected
  * policyRule: code to represent type of Proxy Access
  * patient.identifier: NHSNumber of the subject of the proxy access request
  * performer: who agreed to the proxy access

  * source: proxy access request form (ProxyAccessRequest:QuestionnaireResponse)
  * provision.type: permit
  provision.period: timeframe this proxy request is valid (and then needs to be reviewed)
  * provision.actor.reference.identifier: NHSNumber of the person making the proxy access request (RelatedPerson)
}

object RelatedPerson {
  * patient.identifier: NHSNumber of the subject of the proxy access request
  name: may be useful to prevent call to PDS just to retrieve the name
  * identifier : NHS Number of the person making the proxy access request
  * relationship: mother, father, etc
  extension.consent: Proxy Acccess Request - should not be present when no consent is present
}

object Patient {
  * identifier : NHSNumber
}

object "RelatedPerson:Patient" as p1 {
  * identifier: NHSNumber
}

object "ProxyAccessRequest:QuestionnaireResponse" as qr1 {
    * questionnaire: url of the ProxyAccessRequestFormDefinition
}

object "ProxyAccessRequestFormDefinition:Questionnaire" as q1 {
    * url: url of the ProxyAccessRequestFormDefinition
}


Consent "provision.actor.reference.identifier" ||--||> "identifier" RelatedPerson
Consent "patient.identifier" }|--||> "identifier" Patient
Consent "source" ||--||> "id" qr1

RelatedPerson "identifier" ||--||> "identifier" p1
RelatedPerson "patient.identifier" }|--||> "identifier" Patient

q1 "url"  <--* "questionnaire" qr1


note "This is the same as PDS Patient" as PDSOverlap
note "This is similar to PDS RelatedPerson" as PDS

PDS .. Patient
PDS .. p1
PDSOverlap .. RelatedPerson

@enduml
