@startuml

skin rose

title National Proxy Service


class RelatedPerson {
  +patient.identifier: NHSNumber
  +identifier : NHSNumber
  +relationship
  +extension: ProxyType
}

class Patient {
  +identifier : NHSNumber
}



object "proxy:Patient" as p2 {
  identifier: NHSNumber
}


RelatedPerson "1" -up- "1" p2: patient.identifier
RelatedPerson "1" -up- "1" Patient: identifier

@enduml
