@startuml

hide footbox

title National Proxy Service - View a Relationship


actor User
participant NationalProxy


User -> NationalProxy : View a Relationship \nGET /RelatedPerson?{queryParameters}
NationalProxy --> User: A collection of matching RelatedPerson\nFHIR Bundle (type=searchset)

@enduml
