@startuml


title Create Relationship

:Step 1 - Create a relationship (POST /QuestionnaireResponse);
:Step 2 - Consent resource is created from the submitted form \n(Consent is proposed);
if (Step 3 - Needs Validating?) is (validate) then
:Step 3a - Validate Relationship. \nGP is asked to verify the Consent ;
else
:Step 3b - Automatically Validated or Rejected. ;
endif
:Step 4 - Consent is now either active or rejected;


@enduml
