@startuml

hide footbox

title National Proxy Service


actor User
participant NationalProxy
participant GPSystem
actor GP


User -> NationalProxy : Create a relationship \nPOST /QuestionnaireResponse

NationalProxy -> NationalProxy: Create a Consent resource from the create a relationship \nPOST \Consent
NationalProxy -> NationalProxy: Create a Create Relationship Task

NationalProxy -> User : Send Task (status=requested) notification

alt Needs Validating
NationalProxy -> GPSystem: Validate a relationship \nPOST /Task
GP -> GPSystem: Act on request
GPSystem -> NationalProxy: Create a permission set \nPOST /QuestionnaireResponse (echoes FHIR R5 Permission resource)
GPSystem -> NationalProxy: Update Consent (link to permission) \nPUT /Consent
GPSystem -> NationalProxy: Respond to Validate a relationship \nPUT /Task/{id} (Yes that is fine)
else Automatically Validated
  NationalProxy -> NationalProxy: Create a permission set
  NationalProxy -> NationalProxy: Updated Consent if required
end 
NationalProxy -> NationalProxy : Create Relationship

NationalProxy -> User : Send Task (status=completed) notification

@enduml
