@startuml

hide footbox

title Find Patient

actor "Patient Demographics Consumer" as consumer
actor "Patient Identity Source" as source

consumer -> source: Patient Demographic Query
source --> consumer: Matching Patient Demographics


@enduml
