@startuml

hide footbox

title "Patient Master Identity Registry - Multiple Patients (IHE PMIR UK Mock up)"


participant "Identity Source (e.g. NHS Scotland" as PMIRSource
participant "PMIR (e.g. NHS England PDS)" as PMIRManager
participant "Internal Consumer \nFixed Distribution List" as PMIRConsumerInternal
participant "External Consumer \nPub Sub" as PMIRConsumerPubSub


PMIRSource -> PMIRManager: POST /$process-message (Collection of FHIR Patient) \n PMIR ITI-93
PMIRManager --> PMIRSource: Collection of FHIR Patient with NHS Number (and CHI Number)

loop for each patient
opt Multi Cast Notification Service / FHIR Cast
  PMIRManager -> PMIRConsumerInternal : MCNS including FHIR Patient (with/without CHI Number?)
  PMIRConsumerInternal -> PMIRManager : OK
else FHIR Subscription (e.g. a subscription on registeredPractice)
  PMIRManager -> PMIRConsumerPubSub : FHIR Subscription including FHIR Patient (with/without CHI Number?)
  PMIRConsumerPubSub -> PMIRManager : OK
end
end

@enduml
