@startuml

title Patient Encounter - Inpatient


:Pre Admission;
:Patient Admitted;
:Provide Inpatient Care;
:Patient Discharged;
if (Ongoing care?) is (no) then

else
:Inpatient Patient Discharge;
  fork
    if (hospital/internally provided care) is (yes) then
      :Transfer to Outpatient (inc virtual) ward;
      while (care still required?) is (yes)
        :Outpatient (inc. virtual) Encounters;
      endwhile
      :Patient Discharged (outpatient);
    endif
  fork again
    if (externally provided care) is (yes) then
      :Refer to other provider(s);
    endif
  end fork
endif

@enduml
