@startuml

hide footbox

title Update Patient

actor "Patient Identity Source \n Patient Identity Registry" as source
actor "Patient Identity Consumer" as consumer

source -> source: Update Patient record
source -> consumer: Patient Updated event notification
consumer --> source: Acknowledgement


@enduml
