@startuml

hide footbox

title "Patient Identity Feed plus Notifications"

participant "Patient Identity Source" as PIXSource
participant "Patient Identifier Cross-reference Manager (e.g. PDS or PAS)" as PIXManager
participant "Patient Identifier Consumer" as PIXConsumer

== FHIR RESTful API - update/create ==

PIXSource -> PIXManager : Patient Identity Feed FHIR [ITI-104] \n\n PUT /Patient or \n\n PUT /Patient?identifier=https://fhir.nhs.uk/Id/nhs-number|{nhsNumber}
PIXManager --> PIXSource : Response (created/updated FHIR Patient)
note over PIXManager,PIXConsumer : Notification Methods
alt FHIR Subscription
  PIXManager -> PIXConsumer: FHIR Subscription (FHIR R4 Bundle (history) including FHIR Patient
  PIXConsumer --> PIXManager: Acknowledgement
else FHIR Cast
  PIXManager -> PIXConsumer: FHIR Cast incudes FHIR Patient
  PIXConsumer --> PIXManager: Acknowledgement
else Patient Identity Feed FHIR [ITI-104]
  PIXManager -> PIXConsumer: [ITI-104] PUT /Patient?identifier=https://fhir.nhs.uk/Id/nhs-number|{nhsNumber}
  PIXConsumer --> PIXManager: Acknowledgement (may include updated/created FHIR Patient)
end


@enduml
