@startuml

hide footbox

title "Patient Encounter Feed with FHIR Subscriptions"

participant "Patient Encounter Source" as PIXSource
participant "Subscription Manager" as PIXManager
participant "Patient Encounter Consumer" as PIXConsumer

PIXConsumer -> PIXManager: Resource Subscription\nIHE DSUBm ITI-110
PIXManager --> PIXConsumer : Acknowledgement
opt No matching Patient
  PIXSource -> PIXManager: Resource Publish \nSimilar to IHE DSUBm ITI-111
  PIXManager --> PIXSource : Response

loop for each matching Subscription
    PIXManager -> PIXConsumer: Resource Notify \nSimilar to IHE DSUBm ITI-112
    PIXConsumer --> PIXManager: Acknowledgement
end
end

@enduml
