@startuml

hide footbox

title Create Patient

actor "Patient Identity Source \n Patient Identity Registry" as source
actor "Patient Identity Consumer" as consumer

source -> source: Create Patient record
source -> consumer: Patient Created event notification
consumer --> source: Acknowledgement


@enduml
