@startuml

hide footbox

title Outpatient (inc. Virtual) Encounters

actor "Patient Encounter Supplier \n (Clinical Data Source)" as supplier
actor "Patient Encounter Consumer" as consumer

supplier -> supplier: Patient is referred to service
loop until programme completed
supplier -> consumer : Appointment booking event notification
consumer --> supplier: Acknowledgement

note over supplier: Begin consultation
supplier -> supplier: Record encounter
note over supplier: End consultation
supplier -> supplier: Record is automatically shared with patient and other providers
supplier -> consumer: Outpatient/Virtual Encounter event notification
consumer --> supplier: Acknowledgement
supplier -> supplier: Encounter record is shared via API's with patient and other providers \n Alternatively the record of the encounter can be shared as a clinic letter.
end
supplier -> consumer: Discharge event notification
consumer --> supplier: Acknowledgement
supplier -> supplier : Complete Discharge Report
supplier -> supplier: Discharge Report is shared via API's with patient and other providers
@enduml
