@startuml

hide footbox


title "Patient Demographics Query (PDQm)"


participant "PDS Consumer" as PDSConsumer
participant "PDS Supplier" as PDSSupplier

PDSConsumer -> PDSSupplier : IHE PDQm ITI-78  \nHL7 FHIR GET /Patient?{queryParameters)
PDSSupplier -> PDSConsumer : IHE PDQm ITI-119  \nHL7 Collection of matching patients (FHIR Patient)

@enduml
