@startuml

hide footbox

title "Patient Identity Feed plus Notifications"

participant "PDS Consumer Source" as PIXSource
participant "PDS" as PIXManager

PIXSource -> PIXManager :  PDS Advanced Trace Querys
PIXManager --> PIXSource : Response
opt No matching Patient
  PIXSource -> PIXManager: PDS NHS Number Allocation Request
  PIXManager --> PIXSource : PDS NHS Number Allocation Request Accepted/Rejected
else Matching Patient - Update Demographics
  PIXSource -> PIXManager: PDS Updating patient details
  PIXManager --> PIXSource : Response
end


@enduml
