@startuml


title Online Consultation Provider - Find national demographics record

start
:Find Patient in GP System (IHE PDQm);
switch (Record Found?)
case ( Found )
  :Compare Record;
  :Update Local or GP Record;
case ( Not found )
  :Find PDS record;
  :Register on local record;
  :Create GP Registration Task;
  :Update PDS record (if required);
endswitch
stop

@enduml
