@startuml

hide footbox

title "PDS Demographics Notifications"

participant "PDS" as PIXManager
participant "PDS Middleware" as Middleware
participant "PDS Consumer Recipient" as PIXConsumer

  PIXManager -> Middleware: Demographics Change Event notification
  alt NEMS
    Middleware -> PIXConsumer: FHIR STU3 Messages (which one depends on fields changed)
    PIXConsumer --> Middleware: Acknowledgement
else Multi Cast Notification Service
  Middleware -> PIXConsumer: MCNS Event
  PIXConsumer --> Middleware: Acknowledgement
end

@enduml
