@startuml

hide footbox

participant Source
participant Middleware
participant Consumer


  Source -> Source : Patient is pre-admitted, admitted, discharged, transferred, etc
  opt is an event trigger
    Source -> Middleware: Encounter Event Notification
    loop for each Consumer
      Middleware-> Consumer: Encounter Event notification \n PUT /Encounter?identifier={identifier} or HL7 v2 ADT
    end
  end

@enduml
