@startuml

hide footbox

title "Update patient details"


participant "PDS Consumer" as PDSConsumer
participant "PDS Supplier" as PDSSupplier


== JSON Patch ==

PDSConsumer -> PDSSupplier : PATCH /Patient/{id}
PDSSupplier -> PDSConsumer : response (FHIR Patient)



@enduml
