@startuml

hide footbox


title "Get patient details"


participant "PDS Consumer" as PDSConsumer
participant "PDS Supplier" as PDSSupplier


== FHIR RESTful API - read ==

PDSConsumer -> PDSSupplier : GET /Patient/{id}
note over PDSConsumer,PDSSupplier : {id} in FHIR is transient, so it can change. \n\n it may be better to refactor this as a search parameter e.g. GET /Patient?identifier={id} \n\n This would also be consistent with IHE PDQm and UK Core FHIR Access
PDSSupplier -> PDSConsumer : response (FHIR Patient)


@enduml
