@startuml

hide footbox


title "Search for a patient"


participant "PDS Consumer" as PDSConsumer
participant "PDS Supplier" as PDSSupplier


== FHIR RESTful API - search ==
PDSConsumer -> PDSSupplier : GET /Patient
PDSSupplier -> PDSConsumer : response (collection of FHIR Patient)

@enduml
