@startuml

skin rose

title Personal Demographic Service

class Patient {
  * identifier : NHSNumber
  * name
  * address
  * telecom
  * gender
  * birthDate
  * deceasedDateTime
  * contact
  * generalPractitioner
  * managingOrganization
}

class RelatedPerson {
  identifier : !NHSNumber is not present
  * name
  * address
  * telecom
  * gender
  * patient.identifier: NHSNumber of the related person
  * period
}

class PharmacyPreferences {
  * extension.nominatedPharmacy
  * extension.dispensingDoctorPharmacy
  * extension.medicalApplianceSupplierPharmacy
}

RelatedPerson "identifier" }o--||> "identifier" Patient: The Patient/RelatedPerson linkage
RelatedPerson "patient.identifier" }o--||> "identifier" Patient : Related person
PharmacyPreferences |o--|| Patient

note "The NHS number of the RelatedPerson is missing in PDS, identifier should be populated." as PDS

PDS .. RelatedPerson

@enduml
