@startuml

hide footbox

skin rose

title "NHS Number allocation"


participant "PDS Consumer" as PDSConsumer
participant "PDS Supplier" as PDSSupplier


== FHIR RESTful API - create ==

PDSConsumer -> PDSSupplier : NHS Number allocation request (POST /Patient - FHIR Patient)
alt found
PDSSupplier -> PDSConsumer : error response (FHIR OperationOutcome)
else not found
PDSSupplier -> PDSConsumer : response (FHIR Paatient)
end

@enduml
