@startuml


title NHS Number Allocation

start
:NHS Number Allocation Request;
switch (Existing PDS record found?)
case ( Found )
  :Response with error code;
case ( Not found )
  :Create PDS record;
endswitch
stop

@enduml
