@startuml

hide footbox

title "Patient Identity Feeds (IHE PIX/PIXm)"

participant "Patient Identity Source \n(e.g. Patient Administration System (PAS))" as PEMSource
participant "Trust Integration Engine (TIE)\nor Orchestration Engine" as PEMManager
participant "Patient Identity Consumer" as PEMConsumer


PEMSource -> PEMManager : Patient Identity Feed \n IHE PIX ITI-8 / HL7 v2 ADT A31
PEMManager -> PEMSource : Acknowledgement
loop for each recipient (fixed distribution list)
  alt IHE PIX
  PEMManager -> PEMConsumer : Patient Identity Feed ITI-8 \n HL7 v2 ADT A31
  PEMConsumer -> PEMManager : Acknowledgement
  else IHE PIXm
   PEMManager -> PEMConsumer : Patient Identity Feed ITI-104 \n HL7 FHIR PUT /Patient?identifier={identifier}
   PEMConsumer -> PEMManager : Acknowledgement
  end
end


@enduml
