@startuml

hide footbox

participant "Scheduling Server" as Source
participant Middleware
actor "Patient and/or Practitioner" as Consumer


  Source -> Source : Appointment booked
  opt is an event trigger
    Source -> Middleware: Appointment Event Notification
    loop for each Consumer
      Middleware-> Consumer: Appointment Event notification \n PUT /Appointment, HL7 v2, SMS, email, letter, etc
    end
  end

@enduml
