@startuml


title Structured Data Caputre


mix_actor "User" as user

object "Form Filler" as formFiller

package FormManager {

  class Questionnaire {
  FindingAQuestionnaire() : GET /Questionnaire
  FormPopulation() : POST /Questionnaire/$populate
  }

  class QuestionnaireResponse {
      StoreCompletedForm: POST /QuestionnaireResponse
      FormDataExtraction() : POST /QuestionnaireResponse/$extract
  }
}


package DataResponder as "Clinical Data Respository (DataResponder)" {
    class Observation {

    }
    class Patient {

    }
    class Etc {

    }
}


user <--> formFiller

formFiller --> formFiller: Render Form

formFiller <-- Questionnaire: Retrieve Form
Questionnaire <-- Observation: Form Population
Questionnaire <-- Patient: Form Population
Questionnaire <-- Etc: Form Population

formFiller --> QuestionnaireResponse: StoreCompleted Form
QuestionnaireResponse --> Observation: Form Data Extraction
QuestionnaireResponse "subject" ||--|| Patient
QuestionnaireResponse --> Etc: Form Data Extraction

@enduml
