@startgantt

-- TSAS --

 [Data Standards] as [record] lasts 3 week
  [Interoperability Standards (UK Core and NHS England)] as [teamA] lasts 3 week
 [Enterprise Architecture (Shared Care Records)] as [ihe] lasts 3 week
 [Interoperability Standards (Administration and Clinical)] as [teamB] lasts 4 week
 [Interoperability Standards (Diagnostics, Medications and Workflow)] as [teamC] lasts 4 week
 [Products and Platforms] as [platform] lasts 3 weeks
 [English NHS Solutions] as [nhs] lasts 3 weeks

 [teamA] starts at [record]'s end
  [teamB] starts at [teamA]'s end
   [teamC] starts at [teamA]'s end
  [teamB] starts at [ihe]'s end
    [teamC] starts at [ihe]'s end

 [platform] starts at [teamA]'s end
 [platform] starts at [teamB]'s end
 [platform] starts at [teamC]'s end
  [nhs] starts at [teamA]'s end
 [nhs] starts at [teamB]'s end
 [nhs] starts at [teamC]'s end
@endgantt
