@startgantt

-- Pre TSAS (Success) --


 [Data Model and Dictionary] as [dict] lasts 2 weeks
  [Enterprise Architecture (NHS X)] as [hl7ihe] lasts 3 week
   [Interoperability Standards (Administration and Clinical)] as [teamB] lasts 4 week
   [Product: England HL7 v2 ADT (IHE PDQ and PIX)] as [pdq] lasts 5 week
   [Product: Care Connect RESTful API (IHE QEDm)] as [qedm] lasts 5 week
     [English NHS Solutions] as [nhs] lasts 3 weeks

 [nhs] is colored in GreenYellow/Green

 [pdq] is colored in Yellow
 [qedm] is colored in Yellow

 [dict] is colored in Yellow
  [hl7ihe] is colored in Yellow

  [pdq] starts at [hl7ihe]'s end
 [pdq] starts at [dict]'s end
  [qedm] starts at [hl7ihe]'s end
 [qedm] starts at [dict]'s end
  [teamB] starts at [hl7ihe]'s end
 [teamB] starts at [dict]'s end


 [nhs] starts at [qedm]'s end
  [nhs] starts at [pdq]'s end

@endgantt
